import colors from 'vuetify/es5/util/colors'

export default {
  theme: {
    dark: true,
    themes: {
      dark: {
        primary: '#F7931A',
        red: '#F57D7D',
        green: '#9BE382',
        accent: colors.grey.darken3,
        secondary: colors.amber.darken3,
        info: colors.teal.lighten1,
        warning: colors.amber.base,
        error: colors.deepOrange.accent4,
        success: colors.green.accent3,
      },
    },
  },
  icons: {
    // iconfont: 'ri',
    values: {
      bets: 'ri-bar-chart-grouped-line',
      wallet: 'ri-wallet-line',
      chat: 'ri-chat-3-line',
      notification: 'ri-notification-line',
      people: 'ri-user-line',
      peoples: 'ri-group-line',
      peopleFill: 'ri-user-3-fill',
      lock: 'ri-lock-2-line',
      gift: 'ri-gift-line',
      crown: 'ri-vip-crown-fill',

      clipboard: 'ri-clipboard-fill',
      left: 'ri-arrow-left-line',
      eyeOn: 'ri-eye-fill',
      eyeOff: 'ri-eye-off-fill',
      locale: 'ri-global-line',
      support: 'ri-customer-service-2-line',
      volume: 'ri-volume-up-line',
      send: 'ri-send-plane-fill',
      logout: 'ri-logout-box-line',
      ad: 'ri-advertisement-line',
      up: 'ri-arrow-up-line',
      down: 'ri-arrow-down-line',
      undo: 'ri-arrow-go-back-line',
      linkArrow: 'ri-arrow-right-fill',
      refresh: 'ri-restart-line',
      history: 'ri-history-line',

      complete: 'ri-check-line',
      cancel: 'ri-close-line',
      close: 'ri-close-line',
      delete: 'ri-delete-bin-line', // delete (e.g. v-chip close)
      clear: 'ri-close-line',
      success: 'ri-checkbox-circle-line',
      info: 'ri-information-line',
      warning: 'ri-alarm-warning-line',
      error: 'ri-error-warning-line',
      prev: 'ri-arrow-left-s-line',
      next: 'ri-arrow-right-s-line',
      checkboxOn: 'ri-checkbox-fill',
      checkboxOff: 'ri-checkbox-blank-line',
      checkboxIndeterminate: 'ri-checkbox-indeterminate-fill',
      delimiter: 'ri-checkbox-blank-circle-fill', // for carousel
      sort: 'ri-arrow-up-line',
      expand: 'ri-arrow-sown-s-line',
      menu: 'ri-menu-line',
      subgroup: 'ri-arrow-down-s-line',
      dropdown: 'ri-arrow-down-s-line',
      radioOn: 'ri-radio-button-line',
      radioOff: 'ri-checkbox-blank-circle-line',
      edit: 'ri-edit-line',
      ratingEmpty: 'ri-star-line',
      ratingFull: 'ri-star-fill',
      ratingHalf: 'ri-star-half-line',
      loading: 'ri-refresh-line',
      first: 'ri-skip-back-line',
      last: 'ri-skip-forward-line',
      unfold: 'unfold_more', // TODO
      file: 'ri-attachment-2',
      plus: 'ri-add-line',
      minus: 'ri-subtract-line',
    },
  },
}
